export type PrayerKind = 'prayer' | 'psalm' | 'catechism' | 'responsive' | 'list';

export interface Prayer {
  slug: string;
  title: string;
  subtitle?: string;
  kind: PrayerKind;
  bookPage?: number;
  text?: string;
  items?: string[];
  rubric?: string;
}

export interface PrayerSection {
  id: string;
  title: string;
  icon: string;
  color: string;
  prayers: Prayer[];
}

export const PRAYER_SECTIONS: PrayerSection[] = [
  {
    id: 'morning',
    title: 'Morning Prayers',
    icon: '☀',
    color: '#C97A24',
    prayers: [
      {
        slug: 'morning-trisagion',
        title: 'Trisagion Prayers',
        subtitle: 'Said upon rising',
        kind: 'responsive',
        bookPage: 5,
        rubric: 'In the Name of the Father, and of the Son, and of the Holy Spirit. Amen.\n\nSay three times:',
        text: `Holy God, Holy Mighty, Holy Immortal, have mercy on us.\n\nGlory to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nAll-holy Trinity, have mercy on us. Lord, cleanse us from our sins. Master, pardon our iniquities. Holy God, visit and heal our infirmities, for Thy Name's sake.\n\nLord, have mercy. Lord, have mercy. Lord, have mercy.\n\nGlory to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nOur Father, Who art in heaven, hallowed be Thy Name; Thy kingdom come; Thy will be done on earth as it is in heaven. Give us this day our daily bread; and forgive us our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil.\n\nFor Thine is the kingdom, and the power, and the glory, of the Father, and of the Son, and of the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nLord, have mercy. (12 times)\n\nGlory to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nMore honorable than the Cherubim, and more glorious beyond compare than the Seraphim, thou who without stain barest God the Word, and art truly Theotokos: we magnify thee.`,
      },
      {
        slug: 'morning-prayer-1',
        title: 'Morning Prayer',
        subtitle: 'Prayer of St. Macarius the Great',
        kind: 'prayer',
        bookPage: 5,
        text: `O Lord our God, Who hast granted us forgiveness of sins through repentance, and hast shown to us an example of prayer in Thy holy and God-pleasing servant David, Who didst receive his prayer of repentance, and dost have mercy upon us also; Thou Who alone art good and gracious, though we have sinned greatly: grant us to approach Thee with contrition of heart, and strengthen us to fulfill all Thy commandments; and grant that we may not be carried away by the spirit of wickedness, but be led by the spirit of wisdom and understanding: be Thou our helper in all things, O Lord; for Thou art holy, and to Thee we ascribe glory: to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'morning-prayer-2',
        title: 'Morning Prayer',
        subtitle: 'Second Morning Prayer',
        kind: 'prayer',
        bookPage: 6,
        text: `O God, cleanse me a sinner, and have mercy upon me.\n\nO Lord our God, in Whom we believe and Whose Name above every other name we worship: Grant us, as we rise up from sleep, so to seek after Thy righteousness, that being guarded by Thine angels, and directed in all our ways, we may pass through this life in peace and safety; and, through Thy grace, be brought to everlasting life.\n\nFor to Thee belong all glory, honor and worship: to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'morning-prayer-3',
        title: 'Prayer to the Most Holy Theotokos',
        subtitle: 'Morning Prayer',
        kind: 'prayer',
        bookPage: 6,
        text: `O Theotokos and ever-virgin Mary, intercede for us sinners.`,
      },
      {
        slug: 'morning-prayer-grant-me',
        title: 'Prayer for a Peaceful Day',
        subtitle: 'Morning Prayer',
        kind: 'prayer',
        bookPage: 6,
        text: `O Lord, grant me to greet the coming day in peace. Help me in all things to rely upon Thy holy will. In every hour of the day reveal Thy will to me. Bless my dealings with all who surround me.\n\nTeach me to treat all that comes to me throughout the day with peace of soul and with firm conviction that Thy will governs all. In all my deeds and words, guide my thoughts and feelings. In unexpected events, let me not forget that all are sent by Thee.\n\nTeach me to act firmly and wisely, without embittering and embarrassing others. Give me strength to bear the fatigue of the coming day with all that it shall bring. Direct my will, teach me to pray, and Thou, Thyself, pray in me. Amen.`,
      },
    ],
  },
  {
    id: 'creed',
    title: 'The Creed',
    icon: '✟',
    color: '#8B0E1A',
    prayers: [
      {
        slug: 'the-creed',
        title: 'The Nicene Creed',
        kind: 'prayer',
        bookPage: 7,
        text: `I believe in one God, the Father Almighty, Maker of heaven and earth, and of all things visible and invisible.\n\nAnd in one Lord Jesus Christ, the Son of God, the Only-begotten, Begotten of the Father before all worlds, Light of Light, Very God of Very God, Begotten, not made; of one essence with the Father, by Whom all things were made:\n\nWho for us men and for our salvation came down from heaven, and was incarnate of the Holy Spirit and the Virgin Mary, and was made man;\n\nAnd was crucified also for us under Pontius Pilate, and suffered and was buried;\n\nAnd the third day He rose again, according to the Scriptures;\n\nAnd ascended into heaven, and sitteth at the right hand of the Father;\n\nAnd He shall come again with glory to judge the quick and the dead, Whose kingdom shall have no end.\n\nAnd I believe in the Holy Spirit, the Lord and Giver of Life, Who proceedeth from the Father, Who with the Father and the Son together is worshipped and glorified, Who spake by the Prophets;\n\nAnd I believe in One Holy Catholic and Apostolic Church.\n\nI acknowledge one Baptism for the remission of sins.\n\nI look for the Resurrection of the dead,\n\nAnd the Life of the world to come. Amen.`,
      },
    ],
  },
  {
    id: 'midday',
    title: 'Midday Prayers',
    icon: '◎',
    color: '#276A3D',
    prayers: [
      {
        slug: 'midday-prayer',
        title: 'Midday Prayer',
        kind: 'prayer',
        bookPage: 9,
        rubric: 'Said at noon. Begin with the Trisagion Prayers and Our Father.',
        text: `O Lord Jesus Christ our God, Who hast taught us to pray and not to faint, forgive us, as we approach this midday hour, all our sins, whether of thought, word, or deed, whether voluntary or involuntary, and be with us throughout the remainder of this day, that we may finish it in Thy peace and may pass through life in the light of Thy countenance, for Thou art holy, and to Thee we ascribe glory: to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.`,
      },
    ],
  },
  {
    id: 'evening',
    title: 'Evening Prayers',
    icon: '☽',
    color: '#4A2C4E',
    prayers: [
      {
        slug: 'evening-trisagion',
        title: 'Trisagion Prayers',
        subtitle: 'Said before sleep',
        kind: 'responsive',
        bookPage: 10,
        rubric: 'Begin with the Trisagion Prayers and Our Father (as in Morning Prayers), then:',
        text: `O God, cleanse me a sinner, and have mercy upon me.\n\nLord, have mercy. (12 times)\n\nGlory to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nMore honorable than the Cherubim, and more glorious beyond compare than the Seraphim, thou who without stain barest God the Word, and art truly Theotokos: we magnify thee.`,
      },
      {
        slug: 'evening-prayer-1',
        title: 'Evening Prayer',
        subtitle: 'First Evening Prayer',
        kind: 'prayer',
        bookPage: 10,
        text: `O Lord our God, in Whom we believe and Whose Name we invoke above every other name: grant us, as we go to our rest, refreshment of body and soul.\n\nKeep us from all the fantasies of the Evil One, and from the temptations that assail us. Calm the impulses of carnal desire, and quench the fiery darts of the Evil One that are craftily aimed at us.\n\nGrant us a peaceful and undisturbed night. Free us from all darkness that comes from sin. Amen.`,
      },
      {
        slug: 'evening-prayer-2',
        title: 'Evening Prayer',
        subtitle: 'Second Evening Prayer',
        kind: 'prayer',
        bookPage: 11,
        text: `O Lord God almighty, hear the prayer of us Thy humble servants, and give rest to all our members after the labors of this day, for without Thy help we cannot live nor move, nor have any good thing; upon Thee, O Lord, do we wait.\n\nMay Thine all-holy blessing rest upon all Thy servants, and upon all Thy creatures throughout the night: and in the morning may we rise up to sing praises unto Thee, Whose nature is goodness, Whose essence is love. Amen.`,
      },
      {
        slug: 'evening-prayer-guardian-angel',
        title: 'Prayer to the Guardian Angel',
        subtitle: 'Evening Prayer',
        kind: 'prayer',
        bookPage: 11,
        text: `O holy Angel, attendant of my wretched soul and of my afflicted life, forsake me not, a sinner, neither depart from me for my intemperance. Give no place to the evil demon to subdue me with the oppression of this mortal body; but take me by my wretched and outstretched hand, and lead me in the way of salvation. Amen.\n\nO holy glorious and all-praised Apostle John the Theologian, beloved of Christ: I entreat thee and implore thine intercession, that thou wouldst pray for me to the Lord God, that He grant forgiveness of all my sins. Amen.`,
      },
    ],
  },
  {
    id: 'church-prayers',
    title: 'Prayers in Church',
    icon: '⛪',
    color: '#276A3D',
    prayers: [
      {
        slug: 'on-entering-church',
        title: 'On Entering a Church',
        kind: 'prayer',
        bookPage: 12,
        text: `I will come into Thy house in the multitude of Thy mercy, and in Thy fear I will worship toward Thy holy temple.\n\nO Lord, lead me in Thy righteousness because of mine enemies; make my way straight before Thy face, that I may sing praises unto Thee with all those who love Thy Name, and glorify Thee forever and ever. Amen.`,
      },
      {
        slug: 'on-leaving-church',
        title: 'On Leaving a Church',
        kind: 'prayer',
        bookPage: 12,
        text: `Lord, now lettest Thou Thy servant depart in peace, according to Thy word: For mine eyes have seen Thy salvation, which Thou hast prepared before the face of all people; A light to lighten the Gentiles, and the glory of Thy people Israel. Amen.`,
      },
      {
        slug: 'before-icon-christ',
        title: 'Before the Icon of Christ',
        kind: 'prayer',
        bookPage: 12,
        text: `O Lord Jesus Christ, Son of God, through the prayers of Thy most pure Mother, our holy and God-bearing Fathers and all the Saints, have mercy on us. Amen.\n\nO Lord and Master of my life, grant me not a spirit of sloth, despondency, ambition and idle talk. But grant unto me, Thy servant, a spirit of soberness, humility, patience and love. Yea, O Lord King, grant me to see my own transgressions and not to judge my brother; for blessed art Thou unto the ages of ages. Amen.`,
      },
      {
        slug: 'jesus-prayer',
        title: 'The Jesus Prayer',
        subtitle: 'Said continually throughout the day',
        kind: 'prayer',
        bookPage: 13,
        text: `Lord Jesus Christ, Son of God, have mercy on me, a sinner.`,
      },
      {
        slug: 'before-icon-theotokos',
        title: 'Before the Icon of the Theotokos',
        kind: 'prayer',
        bookPage: 13,
        text: `O most holy Lady Theotokos, who art more honorable than the Cherubim and incomparably more glorious than the Seraphim; thou who without corruption didst bring forth God the Word, and art truly the Mother of God: we glorify thee, we magnify thee and we bow down before thee. Do thou entreat God, Whom thou didst bear, that He have mercy on us and save our souls. Amen.`,
      },
      {
        slug: 'angelic-salutation',
        title: 'The Angelic Salutation',
        subtitle: 'Hail Mary',
        kind: 'prayer',
        bookPage: 14,
        text: `Hail, O Full of Grace, the Lord is with thee. Blessed art thou among women, and blessed is the fruit of thy womb; for thou hast borne the Savior of our souls.`,
      },
      {
        slug: 'to-holy-trinity',
        title: 'To the Holy Trinity',
        kind: 'prayer',
        bookPage: 14,
        text: `O Holy Trinity, glory to Thee!\n\nMost Holy Trinity, have mercy on us. Lord, forgive our sins. Master, pardon our transgressions. Holy One, visit and heal our infirmities for Thy Name's sake. Lord, have mercy. Lord, have mercy. Lord, have mercy. Amen.`,
      },
      {
        slug: 'to-patron-saint',
        title: 'To Your Patron Saint',
        kind: 'prayer',
        bookPage: 14,
        text: `Pray to God for me, O holy (Name), well-pleasing to God; for I turn to thee who art a speedy helper and intercessor for my soul. Amen.`,
      },
      {
        slug: 'to-guardian-angel',
        title: 'To Your Guardian Angel',
        kind: 'prayer',
        bookPage: 14,
        text: `Angel of Christ, holy guardian and protector of my soul and body, forgive me everything wherein I have offended thee every day of my life, and protect me from all influence and temptation of the evil one. May I never again anger God by my sin. Pray for me to the Lord, that He may make me worthy of the grace of the All-holy Trinity, and of the blessed Mother of God, and of all the saints. Amen.`,
      },
    ],
  },
  {
    id: 'daily-life',
    title: 'Prayers for Daily Life',
    icon: '🕊',
    color: '#C97A24',
    prayers: [
      {
        slug: 'at-the-table',
        title: 'Before Meals',
        subtitle: 'Grace Before Table',
        kind: 'prayer',
        bookPage: 15,
        text: `The eyes of all wait upon Thee, O Lord; and Thou givest them their meat in due season. Thou openest Thine hand, and satisfiest the desire of every living thing.\n\nO Christ our God, bless the food and drink of Thy servants, for Thou art holy, always, now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'after-meals',
        title: 'After Meals',
        subtitle: 'Grace After Table',
        kind: 'prayer',
        bookPage: 16,
        text: `We thank Thee, O Christ our God, that Thou hast satisfied us with Thy earthly gifts; deprive us not of Thy heavenly Kingdom, but as Thou camest among Thy disciples, O Savior, and gavest them peace, come to us and save us. Amen.`,
      },
      {
        slug: 'before-work',
        title: 'Before Commencing Any Task',
        kind: 'prayer',
        bookPage: 17,
        text: `O Lord Jesus Christ, Only-begotten Son of Thine eternal Father, Thou hast said with Thy most pure lips: "Without Me ye can do nothing." O Lord my Lord, with faith I embrace in my heart and soul Thy words, and bow the knees of my heart before Thy goodness: Help me, a sinner, to complete this task I am about to begin, in the Name of the Father, and of the Son, and of the Holy Spirit. Amen.`,
      },
      {
        slug: 'for-parents-children',
        title: 'Of Parents for Their Children',
        kind: 'prayer',
        bookPage: 18,
        text: `O Lord Jesus Christ, in Thy mercy, keep my children under Thy divine protection; bestow upon them health of soul and body; grant them a clear mind and an upright heart; bless all their lawful undertakings, and direct them in Thy paths, that they may live in Thy fear, love Thee, and serve Thee faithfully all the days of their life. Forgive me, their parent, who have sinned before Thee, that through my example and by Thy grace, my children may grow up in piety and in the knowledge of Thee, the true God and Savior. Amen.`,
      },
      {
        slug: 'for-relatives',
        title: 'For Relatives and Friends',
        kind: 'prayer',
        bookPage: 18,
        text: `O Lord Jesus Christ, I beseech Thee to pour down Thy blessing upon all my relatives and friends; guard them from all evil both of soul and body; grant them health of body and salvation of soul; that both they and I, serving Thee faithfully in this life, may in the world to come be found worthy of Thy heavenly Kingdom. Amen.`,
      },
      {
        slug: 'for-priesthood',
        title: 'For the Priesthood',
        kind: 'prayer',
        bookPage: 18,
        text: `O Lord Jesus Christ, Good Shepherd of the sheep, Who art wonderful in Thy saints, we beseech Thee to bless our Most Reverend Archbishop N. and all the clergy and laity of this holy Church. Grant them the spirit of wisdom, understanding, and sound doctrine. Keep them in Thy holy fear. Inspire them with zeal for Thy holy work and Thy holy house. Grant them power to preach Thy saving Gospel; and may the fire of Thy holy love continually burn in their hearts. Amen.`,
      },
      {
        slug: 'for-married',
        title: 'Of a Married Person',
        kind: 'prayer',
        bookPage: 19,
        text: `O Lord our God, Who didst call us to the holy estate of Matrimony and dost sanctify those who are united in Thy Name: continue to bless our marriage with Thy heavenly blessing. Grant us love for one another; fill our home with Thy peace; keep us from all strife and discord; and make us worthy, by a holy and blameless life, to partake of Thy heavenly gifts, and at last to stand before Thy throne, giving thanks unto Thee, the Author and Perfecter of every good gift. Amen.`,
      },
      {
        slug: 'for-single',
        title: 'Of a Single Person',
        kind: 'prayer',
        bookPage: 19,
        text: `O Lord God and Savior, Who callest us each in our own station to serve Thee: grant me grace to honor Thee in my body and in my spirit, which are Thine; keep me in purity of thought, word, and deed; preserve me from all temptations of the world, the flesh, and the evil one; and guide my life so that in all things I may do Thy will, and at the last may be found worthy of Thy Kingdom. Amen.`,
      },
      {
        slug: 'prayer-of-a-child',
        title: 'Prayer of a Child',
        kind: 'prayer',
        bookPage: 20,
        text: `O Lord Jesus, Who didst bless the little children and didst take them in Thine arms: bless me, Thy child, with Thy divine blessing. Grant that I may grow in wisdom, in virtue, and in love of Thee. Help me to obey my parents and teachers, to love my brothers and sisters, and to be kind to all. Keep me from all evil, and make me Thy faithful servant all the days of my life. Amen.`,
      },
      {
        slug: 'before-journey',
        title: 'Before a Journey',
        kind: 'prayer',
        bookPage: 20,
        text: `O Lord Jesus Christ our God, the true and living Way, be Thou the companion of my journey; keep and preserve me from all danger, harm and sin; and grant that in the course of my journey and in all my life I may accomplish only that which is pleasing to Thee; and bring me safely to my destination, and to the haven of everlasting salvation. Amen.`,
      },
    ],
  },
  {
    id: 'special-prayers',
    title: 'Prayers in Time of Need',
    icon: '✦',
    color: '#4A2C4E',
    prayers: [
      {
        slug: 'in-time-of-trouble',
        title: 'In Time of Trouble',
        kind: 'prayer',
        bookPage: 21,
        text: `O Lord our God, great, eternal, wonderful in glory, Who keepest covenant and promises for those that love Thee with their whole heart; Who art the Life of the universe, before Whom the hosts of angels stand with trembling, all whose service is accomplished in spirit and in truth: Thou Who art holy and most highly exalted; who dost rest among the saints: be Thou my help in all trouble. For no other help do I know but Thee. Do Thou be my guide and my strength; my light in darkness; my comfort in sorrow; my strength in weakness.\n\nO Lord, forgive all my sins and iniquities, that in all things I may walk worthy of Thee. And hasten, O Lord, to help me, that I may be strengthened in Thy might, and put my trust in Thee. Amen.`,
      },
      {
        slug: 'thanksgiving-after-trouble',
        title: 'Thanksgiving After Trouble',
        kind: 'prayer',
        bookPage: 22,
        text: `I will bless the Lord at all times; His praise shall continually be in my mouth. My soul shall make her boast in the Lord.\n\nO Lord our God, Who art long-suffering to our sins and patient with our transgressions: I render Thee hearty thanks for delivering me from the trouble which has now passed. I acknowledge that this chastisement was sent for my good, that I might be humbled and made to feel my entire dependence upon Thee. Forgive me all my sins, and grant that this affliction may bring forth in me the peaceable fruit of righteousness. Amen.`,
      },
      {
        slug: 'prayer-of-sick-person',
        title: 'Prayer of a Sick Person',
        kind: 'prayer',
        bookPage: 22,
        text: `O Lord my God, I cry unto Thee by day and by night; I bow my knees and lift up my hands unto Thee, beseeching Thee to have mercy upon me, for my body is in great pain and my soul is greatly troubled.\n\nThou art my hope, O Lord. Let Thine ear be attentive to the voice of my supplications. Thou Who healest all diseases and givest strength to the weak: if it be Thy will, restore me to health, that I may again serve Thee and praise Thy holy Name. But if Thou hast ordained otherwise, grant me patience to bear this cross, and may it be unto me for healing of soul, and for the remission of my sins. Amen.`,
      },
      {
        slug: 'after-recovery-sickness',
        title: 'After Recovery from Sickness',
        kind: 'prayer',
        bookPage: 23,
        text: `O Lord my God, I praise and glorify Thy holy Name, and render Thee heartfelt thanks that Thou hast raised me from my bed of sickness and restored me to health. I acknowledge and confess that Thou art the Author and Giver of life and health. Forgive me all my sins past and present; preserve my life from all wickedness; and grant that, profiting by the experience of my late sickness, I may more faithfully and fruitfully serve Thee all the remaining days of my life. Amen.`,
      },
      {
        slug: 'for-the-sick',
        title: 'For the Sick',
        kind: 'prayer',
        bookPage: 24,
        text: `O holy Father, heavenly Physician of our souls and bodies, Who didst send Thine Only-begotten Son our Lord Jesus Christ to heal every sickness and infirmity: visit and heal Thy servant (Name), granting him (her) release from pain, for Thou alone art the Source of healing; through the prayers of our Most Holy Lady Theotokos and of all the saints. Amen.`,
      },
      {
        slug: 'for-the-dead',
        title: 'For the Departed',
        kind: 'prayer',
        bookPage: 24,
        text: `O God of spirits and of all flesh, Who hast trampled down Death and overthrown the Devil, and hast bestowed life on Thy world: Do Thou, the same Lord, give rest to the souls of Thy departed servants (Names), in a place of brightness, a place of refreshment, a place of repose, where all sickness, sighing and sorrow have fled away.\n\nAs Thou art gracious and merciful, pardon every sin committed by them in thought, word, or deed; for there is no man who lives and sins not, Thou only art without sin, and Thy righteousness is to all eternity.\n\nGrant them rest, O Lord, and may Thy light perpetual shine upon them. Amen.`,
      },
      {
        slug: 'general-intercession',
        title: 'A General Intercession',
        kind: 'prayer',
        bookPage: 25,
        text: `O Lord, remember all those who are entrusted to our prayers and who request our prayers:\n\nRemember, O Lord, all those who bear fruit and who do good works in Thy holy churches and who remember the poor. Reward them with Thy rich and heavenly gifts; grant them for earthly things heavenly things; for corruptible things, incorruptible; for temporal things, eternal.\n\nRemember, O Lord, those in the wilderness, in mountains, in dens and caves of the earth; those in virginity and in piety; those in holy matrimony; those in chastity and in the monastic life.\n\nRemember, O Lord, our fathers and brethren away from us; those who are in sickness, in labor, in sorrow, in affliction of every kind; those who need Thy mercy and help, those who love us, those who hate us, and those who have asked us, unworthy as we are, to pray for them.\n\nRemember, O Lord our God, all Thy people, and upon all pour out Thy rich mercy, granting to all their petitions unto salvation. And those whom we have not remembered through ignorance, or forgetfulness, or the multitude of names, do Thou Thyself remember, O God, Who knowest the age and the name of each, Who knowest each one from his mother's womb.\n\nFor Thou, O Lord, art the help of the helpless, the hope of the hopeless, the Savior of the afflicted, the haven of the storm-tossed, the physician of the sick. To Thee do we ascribe glory: to the Father, and to the Son, and to the Holy Spirit, now and ever, and unto ages of ages. Amen.`,
      },
    ],
  },
  {
    id: 'psalm-50',
    title: 'Psalm 50',
    icon: '✦',
    color: '#D4AF37',
    prayers: [
      {
        slug: 'psalm-50',
        title: 'Psalm 50',
        subtitle: 'The Prayer of Repentance',
        kind: 'psalm',
        bookPage: 27,
        rubric: 'Recited frequently; said before Confession.',
        text: `Have mercy upon me, O God, according to Thy lovingkindness; according unto the multitude of Thy tender mercies, blot out my transgressions.\n\nWash me thoroughly from mine iniquity, and cleanse me from my sin.\n\nFor I acknowledge my transgressions, and my sin is ever before me.\n\nAgainst Thee, Thee only, have I sinned, and done this evil in Thy sight: that Thou mightest be justified when Thou speakest, and be clear when Thou judgest.\n\nBehold, I was shapen in iniquity; and in sin did my mother conceive me.\n\nBehold, Thou desirest truth in the inward parts: and in the hidden part Thou shalt make me to know wisdom.\n\nPurge me with hyssop, and I shall be clean: wash me, and I shall be whiter than snow.\n\nMake me to hear joy and gladness; that the bones which Thou hast broken may rejoice.\n\nHide Thy face from my sins, and blot out all mine iniquities.\n\nCreate in me a clean heart, O God; and renew a right spirit within me.\n\nCast me not away from Thy presence; and take not Thy Holy Spirit from me.\n\nRestore unto me the joy of Thy salvation; and uphold me with Thy free spirit.\n\nThen will I teach transgressors Thy ways; and sinners shall be converted unto Thee.\n\nDeliver me from bloodguiltiness, O God, Thou God of my salvation: and my tongue shall sing aloud of Thy righteousness.\n\nO Lord, open Thou my lips; and my mouth shall shew forth Thy praise.\n\nFor Thou desirest not sacrifice; else would I give it: Thou delightest not in burnt offering.\n\nThe sacrifices of God are a broken spirit: a broken and a contrite heart, O God, Thou wilt not despise.\n\nDo good in Thy good pleasure unto Zion: build Thou the walls of Jerusalem.\n\nThen shalt Thou be pleased with the sacrifices of righteousness, with burnt offering and whole burnt offering: then shall they offer bullocks upon Thine altar.\n\nAs giving life, as more splendid than Paradise, and more radiant than any royal chamber, O Christ, is shown forth Thy Tomb, the Fountain of our resurrection.`,
      },
    ],
  },
  {
    id: 'spiritual-helps',
    title: 'Spiritual Helps',
    icon: '📖',
    color: '#6A6453',
    prayers: [
      {
        slug: 'commandments-of-god',
        title: 'The Commandments of God',
        kind: 'list',
        bookPage: 28,
        items: [
          'I am the Lord thy God: thou shalt not have strange gods before Me.',
          'Thou shalt not take the Name of the Lord thy God in vain.',
          'Remember thou keep holy the Lord\'s Day.',
          'Honor thy father and thy mother.',
          'Thou shalt not kill.',
          'Thou shalt not commit adultery.',
          'Thou shalt not steal.',
          'Thou shalt not bear false witness against thy neighbor.',
          'Thou shalt not covet thy neighbor\'s wife.',
          'Thou shalt not covet thy neighbor\'s goods.',
        ],
      },
      {
        slug: 'seven-grievous-sins',
        title: 'The Seven Grievous Sins',
        kind: 'list',
        bookPage: 28,
        items: [
          'Pride',
          'Covetousness',
          'Lust',
          'Envy',
          'Gluttony',
          'Anger',
          'Sloth',
        ],
      },
      {
        slug: 'seven-capital-virtues',
        title: 'The Seven Capital Virtues',
        kind: 'list',
        bookPage: 28,
        items: [
          'Humility',
          'Liberality',
          'Chastity',
          'Brotherly Love',
          'Temperance',
          'Meekness',
          'Diligence',
        ],
      },
      {
        slug: 'nine-ways-sin',
        title: 'Nine Ways of Participating in Another\'s Sin',
        kind: 'list',
        bookPage: 29,
        items: [
          'By counsel',
          'By command',
          'By consent',
          'By provocation',
          'By praise or flattery',
          'By concealment',
          'By partaking',
          'By silence',
          'By defense of the ill done',
        ],
      },
      {
        slug: 'chief-aids-penitence',
        title: 'The Chief Aids to Penitence',
        kind: 'list',
        bookPage: 30,
        items: [
          'Consideration of the grievousness of sin and its consequences.',
          'Consideration of the loss of heaven and the pains of hell.',
          'Consideration of the love of God and the ingratitude of sin.',
          'Hatred of sin and sorrow for having offended God.',
          'Prayer for the grace of contrition and forgiveness.',
          'A firm purpose of amendment and avoiding the occasions of sin.',
          'Frequent and fervent reception of the Holy Sacraments.',
          'Fasting and self-denial.',
          'Works of mercy and charity.',
          'Meditation on the Passion of our Lord Jesus Christ.',
        ],
      },
      {
        slug: 'spiritual-works-mercy',
        title: 'Spiritual Works of Mercy',
        kind: 'list',
        bookPage: 30,
        items: [
          'To instruct the ignorant.',
          'To counsel the doubtful.',
          'To admonish sinners.',
          'To bear wrongs patiently.',
          'To forgive offenses willingly.',
          'To comfort the afflicted.',
          'To pray for the living and the dead.',
        ],
      },
      {
        slug: 'corporal-works-mercy',
        title: 'Corporal Works of Mercy',
        kind: 'list',
        bookPage: 31,
        items: [
          'To feed the hungry.',
          'To give drink to the thirsty.',
          'To clothe the naked.',
          'To shelter the homeless.',
          'To visit the sick.',
          'To visit the imprisoned.',
          'To bury the dead.',
        ],
      },
      {
        slug: 'gifts-holy-spirit',
        title: 'The Gifts of the Holy Spirit',
        kind: 'list',
        bookPage: 31,
        items: [
          'Wisdom',
          'Understanding',
          'Counsel',
          'Fortitude',
          'Knowledge',
          'Piety',
          'Fear of the Lord',
        ],
      },
      {
        slug: 'fruits-holy-spirit',
        title: 'The Fruits of the Holy Spirit',
        kind: 'list',
        bookPage: 31,
        items: [
          'Charity',
          'Joy',
          'Peace',
          'Patience',
          'Benignity',
          'Goodness',
          'Longanimity',
          'Mildness',
          'Faith',
          'Modesty',
          'Continency',
          'Chastity',
        ],
      },
      {
        slug: 'great-feasts',
        title: 'The Great Feasts of the Church',
        kind: 'list',
        bookPage: 32,
        rubric: 'The Twelve Great Feasts of the Orthodox Church:',
        items: [
          'The Nativity of the Theotokos — September 8',
          'The Elevation of the Holy Cross — September 14',
          'The Presentation of the Theotokos — November 21',
          'The Nativity of Christ — December 25',
          'The Theophany (Baptism of Christ) — January 6',
          'The Presentation of Christ — February 2',
          'The Annunciation — March 25',
          'The Entry into Jerusalem (Palm Sunday)',
          'The Ascension — 40 days after Pascha',
          'Pentecost — 50 days after Pascha',
          'The Transfiguration — August 6',
          'The Dormition of the Theotokos — August 15',
        ],
      },
    ],
  },
  {
    id: 'confession',
    title: 'Holy Confession',
    icon: '🕊',
    color: '#8B0E1A',
    prayers: [
      {
        slug: 'preparation-confession',
        title: 'Preparation for Confession',
        kind: 'prayer',
        bookPage: 39,
        rubric: 'Read before coming to the Sacrament of Penance.',
        text: `God does not desire the death of a sinner, but rather that he turn away from his sins and live. In the holy Sacrament of Penance we have the means whereby we may obtain forgiveness of our sins, and be restored to the favor of God, our heavenly Father.\n\nIn order that you may make a good confession, it is necessary for you to prepare yourself carefully. Ask God to give you grace to make a thorough examination of your conscience, courage to make a sincere and complete confession, and strength to amend your way of life in the days to come.\n\nBegin your examination with the time of your last confession; try to recall whether you omitted anything through carelessness, or lapse of memory, or from fear of embarrassment. Examine yourself with the assistance of the form of Self-Examination according to the Ten Commandments of God which follows, and with reference to the informative spiritual helps in this book.\n\nIt is most necessary that you be truly sorry for the sins which you have committed, and that you firmly purpose amendment of your manner of living. Accordingly, when you have finished your examination of conscience, say the Prayer of Repentence (page 17) and Psalm 50 (page 27).`,
      },
      {
        slug: 'self-examination',
        title: 'Self-Examination',
        subtitle: 'According to the Ten Commandments',
        kind: 'prayer',
        bookPage: 43,
        rubric: 'Examine your conscience using each of the following questions:',
        text: `FIRST COMMANDMENT\nHave I believed in God the Father, the Son, and the Holy Spirit? Have I failed to trust in God and His mercy? Have I complained against God in adversity? Have I been thankful for God's blessings? Have I doubted the Christian faith and the teachings of the Church? Have I tried to serve God and keep His Commandments? Have I given way to superstition? Have I frequented the religious meetings of heretics and schismatics? Have I neglected my duties to God through fear of ridicule or persecution? Have I failed to pray to God faithfully? Have I put myself before God?\n\nSECOND COMMANDMENT\nHave I made an idol of any person or thing? Have I given to anyone or anything the worship that is due to God alone? Have I set before myself the holy life of Jesus and tried to imitate Him? Have I read the Holy Scriptures regularly? Have I been irreverent during Church Services? Have I let my attention wander or been insincere? Have I neglected to receive Holy Communion regularly or without due preparation?\n\nTHIRD COMMANDMENT\nHave I profaned the holy name of God in any way? Have I cursed anyone or anything, or sworn a false oath? Have I failed to give proper reverence to holy persons and things? Have I broken any solemn vow or promise? Have I entered into any unlawful contract or made an unlawful promise?\n\nFOURTH COMMANDMENT\nHave I stayed away from Church on Sundays or done unnecessary work on Sundays? Have I spent the day in unwholesome fashion or profaned it by improper conduct? Have I kept the Fasts and Festivals prescribed by the Church?\n\nFIFTH COMMANDMENT\nHave I respected my parents and been obedient to them? Have I been guilty of deception, or caused them pain by my words or actions? Have I neglected them or failed to help them? Have I done my duty towards my family? Have I been wanting in love or kindness towards my husband (or wife), or harmed him (or her) in any way? Have I set my children a good example and tried to bring them up properly? Have I corrected their faults with patience and not with anger? Have I over-indulged or spoiled them?\n\nSIXTH COMMANDMENT\nHave I caused the injury or death of any one, or wished that I were dead? Have I done anything to shorten my own life or that of someone else by injuring health, or through evil and intemperate living? Have I given way to anger, or harmed others with words or actions? Have I failed to help others who needed help, or failed to stand up for those unjustly treated? Have I been cruel to anyone? Have I mistreated animals or destroyed any life unnecessarily? Have I failed to forgive anyone or harbored evil thoughts against them?\n\nSEVENTH COMMANDMENT\nHave I given way to impure thoughts, words, or deeds? Have I committed any unworthy actions alone or with others? Have I degraded myself in any way, or forgotten human dignity? Have I read immoral books or magazines, or delighted in obscenity of any kind? Have I associated with bad companions or frequented unsavory places? Have I eaten or drunk or smoked too much? Have I been lazy, idle, or wasted my time? Have I led others to commit sinful acts? Have I been unfaithful to any trust confided in me?\n\nEIGHTH COMMANDMENT\nHave I stolen anything or wished to do so? Have I kept anything that did not belong to me? Have I tried honestly to find owners of lost articles I have found? Have I cheated anyone? Have I paid my debts? Have I lived within my income, and not wastefully and extravagantly to my means? Have I given to charitable causes in proportion to my means? Have I been honest and upright?\n\nNINTH COMMANDMENT\nHave I told lies, or added to or subtracted from the truth? Have I made careless statements or spoken evil of anyone? Have I told any secrets entrusted to me, or betrayed anyone? Have I gossiped about anyone or harmed their reputation? Have I assisted in carrying out a lie, or pretended to commit a sin of which I was not guilty? Have I tried to see the good in others rather than their shortcomings?\n\nTENTH COMMANDMENT\nHave I envied anything good that has come to others? Have I been jealous of another's good fortune? Have I wished for anything that was another's? Have I damaged or destroyed the property of others? Have I wished for things God has not given me, or been discontented with my lot? Have I been stingy? Have I held back anything from one another? Have I hoped for the downfall of anyone so that I might gain by it? Have I failed to be gracious and generous to anyone? Have I expected to give me that which I would refuse one of my fellow men?`,
      },
      {
        slug: 'order-of-confession',
        title: 'The Order of Confession',
        subtitle: 'A Short Form',
        kind: 'responsive',
        bookPage: 45,
        rubric: 'While the penitent is waiting for the Priest to hear his confessions, he says quietly the Trisagion Prayers and Psalm 50. Then aloud:',
        text: `I have sinned, O Lord: forgive me. O God, be gracious unto me a sinner.\n\n(When the Penitent's turn comes, he goes forward and kneels in the proper place, and says aloud:)\n\nO Father, Lord of heaven and earth, I confess to thee all the hidden and open sins of my heart and mind, which I have committed unto this present day; wherefore I beg of thee, the righteous and compassionate Judge, remission of sins and grace to sin no more.\n\n(The Priest questions the Penitent concerning his sins, and the questioning finished, he says these words:)\n\nMy spiritual child, who hast confessed to my humble self, I humble and a sinner, have not power on earth to forgive sins, but God alone; yet through that divinely spoken word which came to the Apostles after the Resurrection saying: Whatsoever sins ye remit, they are remitted, we too are emboldened to say: Whatsoever thou hast ever said, and whatsoever thou hast not succeeded in saying, either through ignorance, or through forgetfulness. Whatever it may be: God forgive thee in this present world, and in that which is to come.\n\n(And the Priest adds this Prayer, making the sign of the Cross over the Penitent:)\n\nGod it was who forgave David through Nathan the Prophet, when he confessed his sins, and Peter weeping bitterly for his denial, and the sinful woman in tears at his feet, and the Publican, and the Prodigal Son: May that same God forgive thee all things, through me a sinner, both in this present world, and set thee un-condemned before his dread Judgment Seat.\n\n(The Penitent returns to his seat and gives thanks to God for His goodness, saying one or more of the Prayers After Confession which follow.)`,
      },
      {
        slug: 'prayers-after-confession',
        title: 'Prayers After Confession',
        kind: 'prayer',
        bookPage: 47,
        text: `1.\nO almighty and merciful God, I truly thank thee for the forgiveness of my sins; bless me, O Lord, and help me always, that I may ever do that which is pleasing to thee, and sin no more. Amen.\n\n2.\nO Lord God of my salvation, the Saviour and Benefactor of my soul, I am truly sorry for my every transgression and I firmly resolve never again to offend thee by my sins, and sincerely promise to amend my way of life. O Lord, grant me strength to keep this resolution. Amen.\n\n3.\nO Lord and Master of my life! Take from me the spirit of sloth, despondency, ambition and idle talk. But grant unto me, Thy servant, a spirit of soberness, humility, patience and love. Yea, O Lord King, grant me to see my own transgressions and not to judge my brother; for blessed art Thou unto the ages of ages. Amen.\n\n4.\nO God of mercy, have compassion on my weakness and on the frailty of my nature. Grant me the spirit of repentance and contrition. Incline my heart to true conversion, to virtue and to earnest prayer. Give me strength to resist all temptation. And when, through human weakness, I shall fall again into sin, raise me up by the power of Thy grace, and bring me once more to Thy mercy. Amen.\n\n5.\nO Lord Jesus Christ, Who on the Cross didst pray for them that crucified Thee: do Thou forgive my sins and the sins of all men, granting unto me and unto all true repentance and amendment of life. Amen.`,
      },
    ],
  },
  {
    id: 'communion',
    title: 'Holy Communion',
    icon: '✦',
    color: '#D4AF37',
    prayers: [
      {
        slug: 'preparation-communion',
        title: 'Preparation Before Holy Communion',
        subtitle: 'Introduction',
        kind: 'prayer',
        bookPage: 47,
        rubric: 'Before approaching the Holy Chalice, fast from midnight, then say these prayers with contrition:',
        text: `I desire to partake of the divine and holy Mysteries of Thy most pure Body and precious Blood, O Lord Jesus Christ. Therefore, first, I humbly beseech Thee: be merciful to me and forgive my transgressions whether voluntary or involuntary, in word or deed, in knowledge or in ignorance; and make me worthy without condemnation to partake of Thy most pure Mysteries, unto the forgiveness of sins and unto life eternal. Amen.`,
      },
      {
        slug: 'pre-communion-prayer-1',
        title: 'Prayer Before Communion I',
        subtitle: 'Prayer of St. John Chrysostom',
        kind: 'prayer',
        bookPage: 47,
        text: `O Lord my God, I know that I am not worthy or sufficient that Thou shouldest come under the roof of the house of my soul; for it is all deserted and fallen, and Thou hast not in me a fit place to lay Thy head. But as from the height of Thy glory Thou didst humble Thyself for our sake, so now conform Thyself to my humility; and as Thou didst deign to lie in a manger in a cave, so deign also to come into the manger of my dumb soul and corruptible body. And as Thou didst not disdain to enter and dine with sinners in the house of Simon the leper, so deign also to enter into the house of my humble soul all leprous and sinful. And as Thou didst not drive away the harlot like me who came and touched Thee, so also have compassion on me, a sinner, as I come and touch Thee. And grant that I may partake of Thy holy Body and precious Blood for the sanctification, enlightenment and strengthening of my humble soul and body. Amen.`,
      },
      {
        slug: 'pre-communion-prayer-2',
        title: 'Prayer Before Communion II',
        subtitle: 'Prayer of St. Basil the Great',
        kind: 'prayer',
        bookPage: 48,
        text: `O Master and Lord Jesus Christ our God, Source of life and immortality, Creator of all things visible and invisible, co-eternal Son of the eternal Father, out of Thy surpassing goodness Thou didst in these last days clothe Thyself in flesh, Thou wast crucified, and by Thy death didst destroy death, and didst save our fallen race. Having risen on the third day, Thou didst ascend into heaven and sit at the right hand of the Father, having given commandment that this dread and undefiled Mystery should be offered for the remission of sins and unto life eternal.\n\nDeign now also, O Lord, to come to me a sinner and unworthy servant, as I approach Thy holy Mystery. Cleanse me with Thy Holy Spirit; strengthen me with Thy power; grant me to partake of Thy holy Body and precious Blood without condemnation, unto the forgiveness of sins and unto life eternal. For Thine is the kingdom, and the power, and the glory: of the Father, and of the Son, and of the Holy Spirit, now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'pre-communion-prayer-3',
        title: 'Prayer Before Communion III',
        subtitle: 'Prayer of St. Symeon Metaphrastes',
        kind: 'prayer',
        bookPage: 49,
        text: `From the foul flood of my iniquities do Thou receive me, O Thou who art only Love. From the mire of my transgressions do Thou lift me, that I may not be drowned therein, O merciful Lord.\n\nI believe, O Lord, and I confess that Thou art truly the Christ, the Son of the living God, who didst come into the world to save sinners, of whom I am chief. And I believe that this is truly Thine own most pure Body, and that this is truly Thine own precious Blood. Wherefore I pray Thee: have mercy upon me and forgive my transgressions, voluntary and involuntary, in word and deed, in knowledge and in ignorance; and make me worthy to partake without condemnation of Thine immaculate Mysteries, unto the forgiveness of sins and unto life eternal. Amen.`,
      },
      {
        slug: 'pre-communion-prayer-4',
        title: 'Prayer Before Communion IV',
        subtitle: 'Prayer to the Most Holy Theotokos',
        kind: 'prayer',
        bookPage: 50,
        text: `O Lady most holy, Theotokos, the light of my darkened soul, my hope and shelter, my refuge and comfort and joy: I thank thee that thou hast granted me, the unworthy, to partake of the most pure Body and precious Blood of thy Son. Do thou, O Lady, who didst give birth to the true Light, enlighten the mental eyes of my heart. Thou who didst give birth to the Fountain of immortality, grant life to me who am dead in sin. Thou who art the compassionately-loving Mother of the merciful God, have mercy on me and give me contrition and humility in my heart, and a lifting up of my captive thoughts; and grant me until my last breath to receive without condemnation the sanctification of the most pure Mysteries, unto the healing of soul and body. Grant me tears of repentance and thanksgiving, that I may praise and glorify thee all the days of my life, for thou art blessed and most glorified unto the ages. Amen.`,
      },
      {
        slug: 'pre-communion-prayer-5',
        title: 'Prayer Before Communion V',
        subtitle: 'Prayer of St. John Chrysostom',
        kind: 'prayer',
        bookPage: 51,
        text: `O Lord my God, I know that I am not worthy that Thou shouldest enter under the roof of my soul; but as Thou didst not disdain to lie in a manger, so deign to come also into the stable of my soul. As Thou didst not refuse to enter and dine with sinners, so do Thou deign to enter into the house of my humble soul all leprous and sinful; and as Thou didst not drive away the harlot who came and touched Thee, so have compassion also on me, a sinner, as I come and touch Thee.\n\nI believe, O Lord, and I confess that Thou art truly the Christ, the Son of the living God, who didst come into the world to save sinners, of whom I am chief. And I believe that this is truly Thine own most pure Body, and that this is truly Thine own precious Blood. Wherefore I pray Thee: have mercy upon me and forgive my transgressions, voluntary and involuntary, in word and deed, in knowledge and in ignorance; and make me worthy to partake without condemnation of Thine immaculate Mysteries, unto the forgiveness of sins and unto life eternal. Amen.`,
      },
      {
        slug: 'pre-communion-prayer-6',
        title: 'Prayer Before Communion VI',
        subtitle: 'Prayer of St. John of Damascus',
        kind: 'prayer',
        bookPage: 52,
        text: `I stand before the gates of Thy temple, yet I turn not away from evil thoughts. But Thou, O Christ our God, Who didst justify the Publican and didst have mercy on the woman of Canaan and didst open the gates of Paradise to the Thief, open to me the bowels of Thy lovingkindness and receive me as I approach and touch Thee, like the sinful woman and the woman with an issue of blood: the one touched but the hem of Thy garment and was straightway healed; the other embraced Thy most pure feet and received remission of her sins.\n\nBut I, the wretched one, am bold to receive Thy whole Body. Let me not be burnt up, but receive me as Thou didst receive them, and enlighten my soul's senses, consuming my guilt of sin: through the prayers of her who, without seed, gave birth to Thee, and of the heavenly powers; for Thou art blessed unto the ages of ages. Amen.`,
      },
      {
        slug: 'thanksgiving-communion-simeon',
        title: 'Prayer of St. Simeon',
        subtitle: 'After Holy Communion',
        kind: 'prayer',
        bookPage: 53,
        rubric: 'Thanksgiving after Holy Communion. First, read the six Prayers of Thanksgiving, then:',
        text: `Lord, now lettest Thou Thy servant depart in peace, according to Thy word: For mine eyes have seen Thy salvation, which Thou hast prepared before the face of all people; A light to lighten the Gentiles, and the glory of Thy people Israel.\n\nThen say the Trisagion Prayers (page 5), and the following hymns:`,
      },
      {
        slug: 'thanksgiving-communion-apolytikion',
        title: 'Apolytikion of St. John Chrysostom',
        subtitle: 'After Holy Communion',
        kind: 'prayer',
        bookPage: 53,
        text: `The grace of thy mouth, shining forth like a beacon-fire, hath enlightened the civilized world, and bestowed upon all the world treasures of liberality, and shown us the heights of humility. But while thou dost teach us by thy words, O Father John Chrysostom, intercede also with Christ our God, the Word, for the salvation of our souls.`,
      },
      {
        slug: 'thanksgiving-communion-kontakion',
        title: 'Kontakion of St. John Chrysostom',
        subtitle: 'After Holy Communion',
        kind: 'prayer',
        bookPage: 54,
        text: `From heaven thou didst receive grace divine, and with thy lips thou dost teach all to worship the one God in Trinity. O all-blessed and glorious John Chrysostom. Worthily do we praise thee, for thou art indeed a Teacher, who dost reveal the things divine.\n\nThen:\nLord, have mercy. (twelve times.)\n\nGlory to the Father, and to the Son, and to the Holy Spirit: both now and ever, and unto ages of ages. Amen.\n\nMore honorable than the Cherubim, and more glorious beyond compare than the Seraphim, thou who without stain barest God the Word, and art truly Theotokos: we magnify thee.\n\nAnd the Dismissal:\nGlory to thee, O our God; glory to thee.\n\nMay Christ, our true God, through the intercession of His all-immaculate and all-blameless holy Mother; of our Father among the Saints John Chrysostom, and of all the Saints, have mercy on us and save us, forasmuch as He is good and loveth mankind.`,
      },
    ],
  },
  {
    id: 'various-occasions',
    title: 'Prayers for Various Occasions',
    icon: '✦',
    color: '#276A3D',
    prayers: [
      {
        slug: 'trisagion-for-dead',
        title: 'Trisagion for the Dead',
        kind: 'responsive',
        bookPage: 111,
        rubric: 'Said for the departed. Begin with:',
        text: `PRIEST: Blessed is our God always: now and ever, and unto ages of ages. Amen.\n\nHoly God, Holy Mighty, Holy Immortal: have mercy on us. (×3)\n\nGlory to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nAll-holy Trinity, have mercy on us. Lord, cleanse us from our sins. Master, pardon our iniquities. Holy God, visit and heal our infirmities for Thy Name's sake.\n\nLord, have mercy. Lord, have mercy. Lord, have mercy.\n\nGlory to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nOur Father, Who art in heaven, hallowed be Thy Name; Thy kingdom come; Thy will be done on earth as it is in heaven. Give us this day our daily bread; and forgive us our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil.\n\nFor Thine is the kingdom, and the power, and the glory, of the Father, and of the Son, and of the Holy Spirit: now and ever, and unto ages of ages. Amen.\n\nWith the spirits of the righteous made perfect, give rest to the soul of Thy servant, O Saviour; and preserve it in that life of blessedness which is with Thee, O Thou who lovest mankind.\n\nIn the place of Thy rest, O Lord, where all Thy Saints repose, give rest also to the soul of Thy servant; for Thou only lovest mankind.\n\nGlory to the Father, and to the Son, and to the Holy Spirit:\n\nThou art our God, who descended into Hell, and loosed the bonds of those who were there; Thyself give rest also to the soul of Thy servant.\n\nNow and ever, and unto ages of ages. Amen.\n\nO Virgin, pure and immaculate, who without stain didst bring forth God, intercede for the salvation of his soul.\n\nGive rest, O Lord, to the soul of Thy servant (Name), and make his (her) memory to be eternal.`,
      },
      {
        slug: 'blessing-any-object',
        title: 'The Blessing of Any Object',
        kind: 'responsive',
        bookPage: 118,
        text: `PRIEST: Let us pray to the Lord.\n\nO Creator and Author of mankind, Giver of spiritual grace and Bestower of eternal salvation: do Thou, the same Lord, send down from on high Thy Holy Spirit, with a blessing from above, upon this (name of object), that it may be potent unto bodily salvation and succor, and aid unto all who shall desire to make use of it, through Jesus Christ our Lord. Amen.\n\n(The Priest sprinkles the object thrice with holy Water and then gives the Benediction.)`,
      },
      {
        slug: 'blessing-bread-wine-oil',
        title: 'Blessing of Bread, Wine and Oil at Great Feasts',
        kind: 'prayer',
        bookPage: 118,
        text: `O Lord Jesus Christ our God, Who didst bless the five loaves and didst feed the five thousand; Do thou bless these loaves, wheat, wine and oil; and multiply them in this city (or parish, or community), and in all thy world; and sanctify all the faithful who shall partake of them. For it is Thou, O Christ our God, Who dost bless and sanctify all things, and to Thee we ascribe glory, together with thy Father who is from everlasting, and thine all-holy, and good, and life-giving Spirit: now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'blessing-palms',
        title: 'Blessing of Palms at Palm Sunday',
        kind: 'prayer',
        bookPage: 119,
        text: `O Lord our God, that sittest upon the Cherubim, who hast raised up the might of thine Only-begotten Son, our Lord Jesus Christ; that through His Cross and Grave and Resurrection He might save the world; and at whose coming today to Jerusalem, sitting upon his voluntary Passion, the people who sat in darkness and in the shadow of death, taking the symbols of victory, the boughs of trees and branches of palms, did go forth and proclaim the Resurrection, by anticipation. Do Thou, the same Lord, preserve and keep us also who in imitation of them do bear in our hands palms and boughs of trees, on this eve of the feast; that both we and all the multitudes and children who offered unto thee Hosanna may also in hymns and spiritual songs, attain unto the Life-giving Resurrection on the third day, in the same Christ Jesus our Lord, with whom thou art blessed, together with thine all-holy, and good, and life-giving Spirit: now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'blessing-flesh-meats',
        title: 'Blessing of Flesh-Meats at Holy Easter',
        kind: 'prayer',
        bookPage: 120,
        text: `O Lord Jesus Christ our God, upon these flesh-meats which faithful Abraham offered thee, the ram which Thou didst sanctify through Moses the Prophet, bless these flesh-meats which faithful Abraham offered; and also the fatted calf which thou didst command to be slain for thy son who had gone astray, and had returned again to thee; that even as he was accounted worthy to enjoy thy good things, so may we also enjoy these things which are sanctified and blessed by thee, to the nourishment of us all. For thou art our God, mighty in mercy, and Giver of all good things, and to thee we ascribe glory, together with thy Father who is from everlasting, and thine all-holy, and good, and life-giving Spirit: now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'prayer-founding-house',
        title: 'Prayer at the Founding of a House',
        kind: 'prayer',
        bookPage: 122,
        text: `O God Almighty, who hast made the heavens with wisdom, and hast established the earth upon its firm foundations, the Creator and Author of mankind: Look upon thy servant N., to whom it hath been decreed for thee to set up a house; and establish thou the same upon a firm rock, and found it according to thy divine word in the Gospel, so that neither wind nor flood any other thing shall be able to stir it. For thou art God, mighty in mercy, and gracious in strength; and unto thee is due glory: to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'prayer-journey-land',
        title: 'For Those About to Journey by Land',
        kind: 'prayer',
        bookPage: 123,
        text: `O Lord Jesus Christ our God, the true and living Way: Humbly we pray thee, be Thou the companion of this thy servant N.; and guide, preserving and directing him unto the fulfillment of thy commandments; and preserving him in peace, happiness and health; and bringing him back again in safety and tranquillity. And grant that he may fulfill all his good intentions pleasurably, favorably to thy glory. For it is to thee to show mercy, and to save us, and to thee we ascribe glory, together with thy Father who is from everlasting, and thine all-holy, and good, and life-giving Spirit: now and ever, and unto ages of ages. Amen.`,
      },
      {
        slug: 'prayer-journey-water',
        title: 'For Those About to Journey by Water or by Air',
        kind: 'prayer',
        bookPage: 124,
        text: `O Master, Lord Jesus Christ our God, who didst walk upon the waters as upon dry land, and didst rebuke the stormy wind, and command the waves of the sea to be still: We humbly pray thee O Saviour, to sail with this thy servant in his ship, alleviating every unfavorable wind and tempest; and raise up special and timely winds for a successful voyage; being thyself ever unto him a pilot and a saving; an anchor of hope; an untemptuous and tranquil haven; unto him and his ship. And as thou didst save Peter from drowning, so in sovereign wise, deliver thou this thy servant from all assaults of enemies, both visible and invisible, and from misery and distress; and grant that he may return to his home in peace, health and happiness; having accomplished his purpose and entered into the prize. Do Thou richly bestow thine inexhaustible grace upon his deeds, and preserve the ship whole and unharmed. For thou art the Saviour, and the Deliverer, and the rich Giver of all goods, both spiritual and temporal; and unto thee we ascribe glory: to the Father, and to the Son, and to the Holy Spirit: now and ever, and unto ages of ages. Amen.`,
      },
    ],
  },
];

export function getPrayerBySlug(slug: string): Prayer | undefined {
  for (const section of PRAYER_SECTIONS) {
    const found = section.prayers.find((p) => p.slug === slug);
    if (found) return found;
  }
  return undefined;
}

export function getSectionById(id: string): PrayerSection | undefined {
  return PRAYER_SECTIONS.find((s) => s.id === id);
}

export function getAllPrayers(): Prayer[] {
  return PRAYER_SECTIONS.flatMap((s) => s.prayers);
}
